<a href="https://colab.research.google.com/github/Ishwaryaa6369Sivakumar/cdwmain/blob/day2/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gensim


In [ ]:
from gensim.models import Word2Vec, KeyedVectors


In [ ]:
import gensim.downloader as api

In [ ]:
wv=api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
vec_king = wv['king']
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [ ]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [ ]:
vec=wv['king']-wv['man']+wv['queen']
vec

array([-0.19494629, -0.2446289 , -0.09539795,  0.3461914 ,  0.01635742,
       -0.08374023,  0.23876953, -0.42193604, -0.28955078,  0.41699982,
       -0.3466797 , -0.43359375,  0.01025391,  0.1256485 ,  0.06689453,
       -0.09790039,  0.20507812, -0.10098267,  0.08251953,  0.32373047,
        0.4580078 ,  0.24821472, -0.20288086,  0.28955078,  0.10253906,
       -0.03857422, -0.48242188, -0.1081543 ,  0.15527344, -0.15270996,
       -0.21386719, -0.20581055,  0.10595703,  0.63391113, -0.5810547 ,
       -0.3017578 , -0.11279297,  0.39648438, -0.09619141,  0.03613281,
        0.21411133, -0.6088867 ,  0.3408203 ,  0.12298584,  0.29492188,
       -0.00195312, -0.03781128,  0.16821289,  0.15332031,  0.24481201,
       -0.04626465,  0.13183594, -0.2626953 ,  0.17150879, -0.40771484,
        0.02772522, -0.41064453, -0.1862793 ,  0.07617188, -0.10406494,
        0.14550781,  0.41992188,  0.00299072,  0.2758789 ,  0.18359375,
       -0.39794922, -0.07757568,  0.12207031, -0.43115234,  0.42

In [ ]:
vec=wv['king']-wv['man']+wv['women']
vec

array([-0.33984375,  0.06298828, -0.00994873,  0.3305664 ,  0.10327148,
       -0.25854492,  0.19677734, -0.32476807, -0.15917969,  0.45752716,
       -0.39208984, -0.22460938,  0.02929688,  0.31982422, -0.0958252 ,
       -0.05932617,  0.01855469, -0.03945923,  0.01101685,  0.33984375,
        0.10351562,  0.14396667, -0.07641602,  0.06640625, -0.10839844,
       -0.1953125 , -0.3564453 , -0.02124023, -0.16503906, -0.16247559,
       -0.05519104, -0.1003418 ,  0.01464844,  0.23449707, -0.26611328,
       -0.07080078, -0.26904297, -0.00292969, -0.06738281, -0.02050781,
        0.04418945, -0.09326172,  0.12304688,  0.10626221,  0.10290527,
        0.01660156, -0.10791016, -0.0065918 ,  0.17578125,  0.10028076,
        0.22363281, -0.05761719, -0.31743622,  0.3922119 , -0.35498047,
       -0.23643494, -0.01074219, -0.01334572, -0.15283203, -0.00793457,
        0.08203125,  0.09985352,  0.003479  ,  0.11608887,  0.14550781,
       -0.125     , -0.11254883,  0.2548828 , -0.04345703,  0.34

In [ ]:
wv.most_similar(vec)

[('king', 0.6478992700576782),
 ('queen', 0.535493791103363),
 ('women', 0.5233659148216248),
 ('kings', 0.5162314772605896),
 ('queens', 0.4995364248752594),
 ('kumaris', 0.49238473176956177),
 ('princes', 0.46233269572257996),
 ('monarch', 0.45280295610427856),
 ('monarchy', 0.4293173849582672),
 ('kings_princes', 0.42342400550842285)]

In [1]:
from google.colab import files
uploaded = files.upload()

Saving path_to_dataset.csv to path_to_dataset.csv


In [2]:
import pandas as pd

data = pd.read_csv("path_to_dataset.csv")
print(data.head())

                        Review_Text  Sentiment
0             This book is amazing!          1
1              Not worth the money.          0
2                I loved the story!          1
3  Poor quality, very disappointed.          0
4        The writing was beautiful.          1


In [3]:
import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from gensim.models import Word2Vec

data = pd.read_csv("path_to_dataset.csv")
data.columns = ["Review_Text", "Sentiment"]

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

data["Review_Text"] = data["Review_Text"].apply(preprocess_text)


tfidf_vectorizer = TfidfVectorizer(max_features=5000)
tfidf_features = tfidf_vectorizer.fit_transform(data["Review_Text"])


sentences = [review.split() for review in data["Review_Text"]]
word2vec_model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

def get_word2vec_features(text):
    words = text.split()
    vector = np.mean([word2vec_model.wv[word] for word in words if word in word2vec_model.wv] or [np.zeros(100)], axis=0)
    return vector

word2vec_features = np.array([get_word2vec_features(review) for review in data["Review_Text"]])

def train_and_evaluate(features, labels):
    X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)


    models = {
        "Logistic Regression": LogisticRegression(),
        "SVM": SVC(),
    }

    results = {}
    for model_name, model in models.items():

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)


        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, zero_division=1)
        recall = recall_score(y_test, y_pred, zero_division=1)
        f1 = f1_score(y_test, y_pred, zero_division=1)

        results[model_name] = {
            "Accuracy": accuracy,
            "Precision": precision,
            "Recall": recall,
            "F1-Score": f1,
        }
    return results

print("Evaluating TF-IDF features")
tfidf_results = train_and_evaluate(tfidf_features, data["Sentiment"])

print("Evaluating Word2Vec features")
word2vec_results = train_and_evaluate(word2vec_features, data["Sentiment"])

print("TF-IDF Results:")
print(pd.DataFrame(tfidf_results).T)

print("\nWord2Vec Results:")
print(pd.DataFrame(word2vec_results).T)

Evaluating TF-IDF features
Evaluating Word2Vec features
TF-IDF Results:
                     Accuracy  Precision  Recall  F1-Score
Logistic Regression       0.0        0.0     1.0       0.0
SVM                       0.0        0.0     1.0       0.0

Word2Vec Results:
                     Accuracy  Precision  Recall  F1-Score
Logistic Regression       0.0        0.0     1.0       0.0
SVM                       0.0        0.0     1.0       0.0
